project:
  type: website
  output-dir: docs
  preview:
    port: 4000

website:
  title: "OohLaLab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    embed-resources: true
    css: styles.css
    toc: true
    toc-title: Contents

lightbox: true
