project:
  render:
    - "*.qmd"
    - "!dev/"
  type: website
  output-dir: docs
  preview:
    port: 4000

website:
  title: "OohLaLab"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: search.qmd
        text: Search
      - sidebar:learn

  sidebar:
    - id: learn
      title: "Learn"
      style: "docked"
      collapse-level: 2
      href: learn/index.qmd
      contents:
        - href: learn/index.qmd
          text: "Introduction"
        - text: "---"
        - section: "Descriptive Statistics"
          contents:
            - href: learn/descriptive-statistics/average-median-and-mode.qmd
              text: Average, median and mode
            - href: learn/descriptive-statistics/standard-error-and-variance.qmd
              text: Standard error and variance
            - href: learn/descriptive-statistics/my-first-article.qmd
              text: My First Article
        - text: "---"

format:
  html:
    theme: journal
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    embed-resources: true
    css: [style/main.css, style/clean-link.css]
    toc: false
    toc-title: Contents

lightbox: true
