[project]
name = "oohlalab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "pre-commit>=4.1.0",
    "ruff>=0.11.0",
]
