name: Deploy Quarto Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Python version
        id: python-version
        run: |
          PYTHON_VERSION=$(cat .python-version)
          echo "python_version=${PYTHON_VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python-version.outputs.python_version }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr"))'

      - name: Install Quarto dependencies
        run: |
          quarto install tinytex
          quarto check

      - name: Render site
        run: quarto render

      - name: Deploy to gh-pages branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ./
          publish_branch: gh-pages
